### ISSUE TITLE
Please add a way to read a password from the TTY even if stdin is not connected to the TTY

### ISSUE THREAD

**Issue by teythoon** [conradkdotcom/rpassword#23]
This allows us to `echo huhu | sq encrypt --symmetric` and prompt for a password.

**Comment by nwalfield** [comment]
Note: not having support for this introduces a potential security issue: because `sq encrypt` reads the password (via rpassword) and the content to encrypt from stdin, the password becomes the first line of the file!

**Comment by conradkdotcom** [comment]
Would you mind telling me what `sq` is ?

**Comment by nwalfield** [comment]
Of course, sorry!  That is the command line interface for Sequoia, an OpenPGP implementation like gpg.  Please see: https://gitlab.com/sequoia-pgp/sequoia https://sequoia-pgp.org

**Comment by conradkdotcom** [comment]
Oh, alright, well that makes sense then !

Feel free to add support through a PR, I'll be glad to review and merge as long as it doesn't contain breaking changes :+1:

**Comment by conradkdotcom** [comment]
Well, I mean, actually, breaking changes are OK but should be avoided if possible. I'll just bump the major version if there is a breaking change.

**Comment by conradkdotcom** [comment]
https://github.com/conradkdotcom/rpassword/pull/26
