### ISSUE TITLE
Windows and Bash

### ISSUE THREAD

**Issue by longshorej** [conradkdotcom/rpassword#27]
Hi! Thanks for rpassword! Currently using it in a cross-platform CLI application.

When on Windows, using cmd or Powershell, all is well. Similarly, macOS and GNU/Linux with bash work fine.

When running on Windows via bash, e.g. Git Bash, calls to `read_password_from_stdin` fail because there's no Windows console available.

I've used the following really hacky workaround, but I'm curious if you have any ideas for a better solution. I did try enabling the Unix module when compiling rpassword on Windows, but libc for Windows naturally doesn't implement many of the required functions or constants, e.g. `tcsetattr`, so it fails to compile.

Here's the hack which spawns bash to read the password, for anyone else that may be stuck on this issue:

```rust
            #[cfg(windows)]
            let windows_git_bash_shell = env::var("SHELL").unwrap_or_default();

            #[cfg(not(windows))]
            let windows_git_bash_shell = "".to_string();

            if windows_git_bash_shell.ends_with("bash.exe") {
                // For some reason, this fails unless read is done twice.
                let password = Command::new(windows_git_bash_shell)
                    .stdin(Stdio::inherit())
                    .arg("-c")
                    .arg("{ read -s password || read -s password; } && echo -n \"$password\"")
                    .output()
                    .ok()
                    .and_then(|output| str::from_utf8(&output.stdout).ok().map(|s| s.to_string()))
                    .unwrap_or_default();

                self.output("\r\n");

                password
            } else {
                rpassword::read_password().unwrap_or_default()
            }
}
```

**Comment by longshorej** [comment]
Sorry for the slow response @conradkdotcom. To confirm, yes, this happens on `master`.

**Comment by conradkdotcom** [comment]
Hello @longshorej ! Are you still interested in getting this fixed ? Otherwise, I'll have to close this issue, as unfortunately, I don't have time to invest in Windows support for this.

**Comment by longshorej** [comment]
I'll close it - the workaround above has us moving forward. I don't think that should belong in library code though, better to keep the hacks in the applications :smile:
