### ISSUE TITLE
When will the latest code be pushed to crates.io?

### ISSUE THREAD

**Issue by Towerism** [conradkdotcom/rpassword#28]
The crate on crates.io hasn't been udpated in over a year. Important changes like being able to call read_password_from_tty is only available from git.

**Comment by conradkdotcom** [comment]
@Towerism Hi ! Sorry about that, it boils down to me not getting replies to my comments on https://github.com/conradkdotcom/rpassword/pull/26. I was unsure if I should publish or not. Is the current `master` version usable for you ? Could you give it a try if you haven't already and confirm ? I can then publish that.

**Comment by conradkdotcom** [comment]
@Towerism Sorry about that, I'll be doing that now. Will update in a few minutes once it's done.

**Comment by conradkdotcom** [comment]
@Towerism Alright, so I've just published as 2.1.0, up from 2.0.0, since there was a feature addition but no breaking change.

Thanks for your time, testing and all ! Please let me know if you run into any issues down the road.

Cheers !

**Comment by conradkdotcom** [comment]
@Towerism Just documented the release as well.

https://github.com/conradkdotcom/rpassword/releases/tag/v2.1.0
