### ISSUE TITLE
inconsistent behavior on Windows

### ISSUE THREAD

**Issue by promethe42** [conradkdotcom/rpassword#32]
Hi,

I'm using rpassword in a cross-platform CLI app.

I have an issue on Windows: after pressing "enter" to validate the password, there is no new line added to the terminal.

![image](https://user-images.githubusercontent.com/998703/54308625-aa0bf280-45ce-11e9-9d3f-f40d60656251.png)

The behavior is different on Llinux:

![image (5)](https://user-images.githubusercontent.com/998703/54308744-f2c3ab80-45ce-11e9-97d9-518b3f5ec7aa.png)

Here is my code:

```rust
trace!("prompt for passphrase");
let pass_string = rpassword::prompt_password_stderr(passphrase_prompt.as_str())
    .unwrap();

trace!("passphrase fetched from command line");
```

Am I doing something wrong?

**Comment by conradkdotcom** [comment]
@promethe42 Hello and thanks for your question. I do not use Windows and thus do not really know how well the crate works on Windows. Unfortunately, I do not have time to invest in testing the crate properly for Windows at the current time.

If @equalsraf or @retep998 happen to have time, they may be able to help.

If you work out the problem, I'm happy to review/test/merge a PR.

**Comment by retep998** [comment]
This crate disables `ENABLE_ECHO_INPUT` so that the password is not printed to the console, but this also prevents the enter key from being printed resulting in no newline. You'd have to manually print out a newline after inputting the password.

**Comment by promethe42** [comment]
> This crate disables ENABLE_ECHO_INPUT so that the password is not printed to the console, but this also prevents the enter key from being printed resulting in no newline.

Not on Linux. Which is kinda the whole issue here.
I expect the behavior to be the same on both platforms and not have to do this kind of dirty tricks:

https://github.com/aerys/gpm/blob/master/src/gpm/ssh.rs#L183

**Comment by retep998** [comment]
By "you" I meant `rpassword`, so `rpassword` would have to manually print out the newline on Windows.

**Comment by conradkdotcom** [comment]
@promethe42 Would you be open to opening a pull request for this change ?

**Comment by conradkdotcom** [comment]
@retep998 Thanks for your help ! :+1:

**Comment by promethe42** [comment]
@conradkdotcom any hint as of where is the code I should fix? Any help appreciated.

**Comment by conradkdotcom** [comment]
@promethe42 Sure ! You could probably print a newline on line 225 of `lib.rs`:
https://github.com/conradkdotcom/rpassword/blob/master/src/lib.rs#L225

**Comment by conradkdotcom** [comment]
@promethe42 Give it a try and let me know if it works out :slightly_smiling_face:

**Comment by joshuef** [comment]
Just came across this as we were having a similar issue (using two `rpassword` inputs one after another).

https://github.com/conradkdotcom/rpassword/pull/33

Implements the fix you suggested @conradkdotcom, and we tested it on windows/osx and it's looking good 👍

**Comment by conradkdotcom** [comment]
Awesome, thanks @joshuef !
